const inventario = [
  {
    sku: 2801,
    linea: "Pinturas",
    contenido: "24 ml",
    nombre: "Calth Blue Clear",
    marca: "Citadel",
    uso: "Aerografo",
    precio: 6000,
    destacado: 1,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669819441/Blueclear_jwdhmt.jpg",
  },
  {
    sku: 2802,
    contenido: "24 ml",
    linea: "Pinturas",
    nombre: "Contrast Ironjawz Yellow",
    marca: "Citadel",
    uso: "Aerografo",
    precio: 6000,
    destacado: 0,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669819441/ironjawzyellow_qeye0s.jpg",
  },
  {
    sku: 2803,
    contenido: "18 ml",
    linea: "Pinturas",
    nombre: "Contrast Militarum Green",
    marca: "Citadel",
    uso: "Pincel",
    precio: 6000,
    destacado: 0,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669819441/greenmilitarum_eaubxx.jpg",
  },
  {
    sku: 1001,
    linea: "Warhammer 40K",
    nombre: "Space Marines Devastators Squad",
    faccion: "Space Marines",
    precio: 39990,
    destacado: 1,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669819056/marines_cfo6v3.jpg",
  },
  {
    sku: 1002,
    linea: "Warhammer 40K",
    nombre: "Warrios with Canoptek Scarabs",
    faccion: "Necron",
    precio: 30000,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669818506/necrons_qiifvd.jpg",
  },
  {
    sku: 1003,
    linea: "Warhammer 40K",
    nombre: "Fire Warriors",
    faccion: "Tau Empire",
    precio: 45000,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669818497/125912858_kjzv38.jpg",
  },
  {
    sku: 2001,
    linea: "Tabletop",
    nombre: "Glommhaven",
    precio: 120000,
    destacado: 1,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669819677/gloom_ux7zrq.jpg",
  },
  {
    sku: 2002,
    linea: "Tabletop",
    nombre: "Scythe",
    precio: 90000,
    destacado: 0,
    img: "https://res.cloudinary.com/dzhtmtpav/image/upload/v1669819787/scythe-box_uiydai.png",
  },
  {
    sku: 2003,
    linea: "Tabletop",
    nombre: "Lotr: The Confrontation",
    precio: 90000,
    destacado: 0,
    img: "https://dementegames.cl/4202-large_default/dune-imperium.jpg",
  },
];

module.exports = inventario;
